name: CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "docs/**"
      - ".gitignore"
  workflow_dispatch:

jobs:
  deploy:
    name: Build And Deploy Docker To EC2
    runs-on: self-hosted

    env:
      APP_DIRECTORY: ${{ github.workspace }}
      CONTAINER_NAME: "fintechbackend"
      APP_PORT: "8000"
      APP_HEALTH_URL: "http://127.0.0.1:8000/health"
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REPOSITORY_NAME: ${{ secrets.ECR_REPOSITORY_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login To Amazon ECR
        id: login_ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Prepare Docker Host
        uses: ./.github/actions/prepare-docker-host
        with:
          app-directory: ${{ env.APP_DIRECTORY }}
          container-name: ${{ env.CONTAINER_NAME }}
          service-name: "fintechbackend"

      - name: Build And Push Image
        id: build_push
        uses: ./.github/actions/build-push-ecr
        with:
          app-directory: ${{ env.APP_DIRECTORY }}
          ecr-registry: ${{ steps.login_ecr.outputs.registry }}
          ecr-repository: ${{ env.ECR_REPOSITORY_NAME }}
          image-tag: ${{ github.sha }}

      - name: Deploy Docker Container
        uses: ./.github/actions/deploy-docker-ec2
        with:
          app-directory: ${{ env.APP_DIRECTORY }}
          container-name: ${{ env.CONTAINER_NAME }}
          image-uri: ${{ steps.build_push.outputs.image-uri }}
          host-port: ${{ env.APP_PORT }}
          container-port: ${{ env.APP_PORT }}
          health-url: ${{ env.APP_HEALTH_URL }}
          database-url: ${{ secrets.DATABASE_URL }}
          secret-key: ${{ secrets.SECRET_KEY }}
          algorithm: HS256
          access-token-expire-minutes: "60"
